### ISSUE TITLE
Track on border color uses track on fill color

### ISSUE THREAD

**Issue by simonbromberg** [Shaninnik/PWSwitch#2]
It seems that the track on border color is set to the track on fill color. Why isn't there a separate property for this?

**Comment by Shaninnik** [comment]
Because fill-in animation for ON state is made with borderWidth transition so that the border becomes same width as button itself filling it, so border color becames fill color, and actual fill color of the layer will do nothing. It is possible to add separate 'real' border color and border, but will require adding another layer. Is it what you are looking for?
